### ISSUE TITLE
ImportError: arg(): could not convert default argument 'param: open3d::geometry::KDTreeSearchParamHybrid' in function 'detect_boundary_points' into a Python object (type not registered yet?)

### ISSUE THREAD

**Issue by dbdxnuliba** [yuecideng/Misc3D#34]
I compile and install misc3d 0.4.0 version
and open3d version is 0.16.1
$ python
Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import open3d as o3d
INFO - 2023-05-25 12:27:54,039 - utils - NumExpr defaulting to 8 threads.
/home/dell/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
>>> import misc3d as m3d
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dell/ref/Misc3D-main/build/install/misc3d/lib/python/misc3d/__init__.py", line 1, in <module>
    from .py_misc3d import *
ImportError: arg(): could not convert default argument 'param: open3d::geometry::KDTreeSearchParamHybrid' in function 'detect_boundary_points' into a Python object (type not registered yet?)
>>>

**Comment by yuecideng** [comment]
Hi @dbdxnuliba , how did you install open3d? did you build it from source and install the python pybind by running `make install-pip-package`?

**Comment by dbdxnuliba** [comment]
yes , but I use open3d version is 0.16.1 ,is the version is too old

**Comment by yuecideng** [comment]
open3d with version >= 16 is acceptable. I think the problem might be 1. the inconsistent of the compilation configuration (eg. different version of compiler gcc/g++). 2. The linking problem of `libOpen3D.so` (check `libMisc3D.so` can find the correct `libOpen3D.so` by using `ldd -r xxx/libOpen3D.so`

**Comment by Jingranxia** [comment]
Hello, have you solved your problem? I also encountered the same problem
